# Site settings
title: Mayron Ceccon
email: mayron.ceccon@gmail.com
description: > 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mayronceccon.github.io" # the base hostname & protocol for your site
twitter_username: mayronceccon
github_username:  mayronceccon
linkedin_username: mayronceccon

disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: mayronceccon

# Build settings
#markdown: kramdown

timezone: America/Sao_Paulo

permalink: /:title